### ISSUE TITLE
generate.sh links to static assets incorrectly in development

### ISSUE THREAD

**Issue by marvinmarnold** [libre-mesh/lime-web#3]
After running `./generate.sh` on local machine, links to stylesheets incorrectly point to an absolute `/css/` directory.  The logo referenced in `lime.css` similarly points to an absolute `url("/logo/logo.png")` which is not correct locally. 

I guess these links work in production but would be nice to have styles and images when developing.

**Comment by p4u** [comment]
You are right but it does not apply after the redesignt to use jekyll.
